name: Unit and integration tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl:
          - '5.16'
          - '5.20'
          - '5.26'
          - '5.30'
          - '5.34'
          - '5.38'
          - '5.40'
          - latest
        include:
          - os: macos-latest
            perl: '5.26'
          - os: macos-latest
            perl: latest
      fail-fast: false
    name: 🐪 Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl -V
        run: perl -V
      - name: Set up perl
        run: |
          cpanm --with-feature=ci --installdeps --notest .
          perl Build.PL
          ./Build build
      - name: Run tests
        if: matrix.perl != 'latest'
        run: |
          TEST_SHARED=1 TEST_SUBREAPER=1 prove -l t
      - name: Run tests with coverage
        if: matrix.perl == 'latest'
        run: |
          TEST_SHARED=1 TEST_SUBREAPER=1 PERL5OPT="-MDevel::Cover=-coverage,statement" prove -l t
          cover -report codecovbash
          curl https://raw.githubusercontent.com/okurz/retry/refs/heads/main/count-fail-ratio > count-fail-ratio
          chmod +x count-fail-ratio
          TEST_SHARED=1 TEST_SUBREAPER=1 PERL5OPT="-MDevel::Cover=-coverage,statement" runs=1000 ./count-fail-ratio prove -l t
      - name: Upload coverage to ☂️ Codecov
        uses: codecov/codecov-action@v5
        if: matrix.perl == 'latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
